### ISSUE TITLE
Not working anymore with the latest windows updates

### ISSUE THREAD

**Issue by uakdemir** [geersch/WPD#1]
Hi - firstly thank you for this great tutorial.

I wanted to tell you that the code is not working anymore after a troublesome windows update
http://forum.notebookreview.com/threads/microsoft-released-a-bad-update-that-broke-mtp-in-windows.802593/

even though windows fixed the issue and we are able to see the device and the SD card connected via usb to the laptop - we are not able to access it anymore. In case you are supporting the code. 

Kind regards

**Comment by geersch** [comment]
Thanks, but I'm not supporting this code. Take it as it is.

2017-12-27 11:02 GMT+01:00 uakdemir <notifications@github.com>:
